@api = http://localhost:8082/Usuarios 

@api2 = http://localhost:8082/Paises

@api3 = http://localhost:8082/Puestos

@api4 = http://localhost:8082/Empleados

@api5 = http://localhost:8082/Proveedores

@api6 = http://localhost:8082/Roles

@api7 = http://localhost:8082/Licores

@api8 = http://localhost:8082/Vinos

@api9 = http://localhost:8082/Marcas

@api10 = http://localhost:8082/Comestibles

@api11 = http://localhost:8082/Tecnologias

@api12 = http://localhost:8082/Privilegios

@api13 = http://localhost:8082/Especialidades

@api14 = http://localhost:8082/Gaseosas

@api15 = http://localhost:8082/BebidasCalientes

@api16 = http://localhost:8082/BebidasHeladas

GET {{api}}

###
GET {{api}}/660c343b299ec4fd1094871c

###
POST {{api}}
Content-Type: application/json

{
    "nombre":"Diana",
    "primerApellido":"Corrales",
    "SegundoApellido":"Gamboa",
    "telefono":89165599,
    "usuario":"ldcorrales",
    "contrasena":"prueba",
    "privilegio":"ADM"
}

###
DELETE {{api}}/660f715a242f3fcbf9de263a

###
PATCH {{api}}/660c343b299ec4fd1094871c
Content-Type: application/json

{
"codigo": "TEC-1",
"nombre": "asdfasdf",
"marca": "asdfasdf",
"restaurante":"Piccola Stella",
"cantidad": 3,
"descripcion": "Equipo de recepcion, cajas, administracion y cocina"
}

###
GET {{api2}}

###
GET {{api2}}/660c6d74cce26a8c73737bc3

###
POST {{api2}}
Content-Type: application/json

{
    "codigo":"CR1",
    "nombre":"Costa Rica"
}

###
DELETE {{api2}}/660c6d74cce26a8c73737bc3

###
PATCH {{api2}}/660f7bd4f28d6350c4bea1fd
Content-Type: application/json

{
    "codigo":"CR1",
    "nombre":"afsdfasdf Rica"
}


###
GET {{api3}}

###
GET {{api3}}/660c703a20a967c63d6817c2

###
POST {{api3}}
Content-Type: application/json

{
    "codigo":"MES",
    "nombre":"Administrador",
    "rol":"Mesero"
}

###
DELETE {{api3}}/660f6fad14656eeee3a6edfe

###
PATCH {{api3}}/660c703a20a967c63d6817c2
Content-Type: application/json

{
    "codigo":"MES",
    "nombre":"asdfasdf",
    "rol":"Mesero"
}

###
GET {{api4}}

###
GET {{api4}}/660c76c7c30c13150eb0c529

###
POST {{api4}}
Content-Type: application/json

{
"codigo": "1",
"nombre": "Alejandro",
"primerApellido": "Rodriguez",
"segundoApellido": "Carvajal",
"cedula": "109380938",
"telefono": 88179988,
"puesto":"Administrador",
"nacionalidad": "Costarricense",
"restaurante": ""
}

###
DELETE {{api4}}/660c76c7c30c13150eb0c529

###
PATCH {{api4}}/660f765f549b366506987851
Content-Type: application/json

{
"codigo": "1",
"nombre": "David",
"primerApellido": "Rodriguez",
"segundoApellido": "Quiros",
"cedula": "109380938",
"telefono": 88179988,
"puesto":"Administrador",
"nacionalidad": "Costarricense",
"restaurante": ""
}

###
GET {{api5}}

###
GET {{api5}}/660c7ac1163ba33084a94b47

###
POST {{api5}}
Content-Type: application/json

{
"codigo": "1",
"nombre": "Vinos y Más",
"ingreso": "21/06/2019",
"correo": "vinoscr@gmail.com",
"telefono": 88752376,
"direccion":"San José"
}

###
DELETE {{api5}}/660f6f10ebb2bd03e0d30f8c

###
PATCH {{api5}}/660f7f1a84aedf331d22e3fa
Content-Type: application/json

{
"codigo": "1",
"nombre": "asdfa y Más",
"ingreso": "21/06/2019",
"correo": "vinoscr@gmail.com",
"telefono": 88752376,
"direccion":"San José"
}


###
GET {{api6}}

###
GET {{api6}}/660c7d968da6948f9db02ffe

###
POST {{api6}}
Content-Type: application/json

{
"codigo": "ROL-1",
"nombre": "Chef",
"descripcion": "Jefe de turno de la cocina"
}

###
DELETE {{api6}}/660c7d968da6948f9db02ffe

###
PATCH {{api6}}/660f8074d498ac393a48eda1
Content-Type: application/json

{
"codigo": "ROL-1",
"nombre": "asdfasdf",
"descripcion": "Jefe de turno de la cocina"
}

###
GET {{api7}}

###
GET {{api7}}/660c86b512f2dc536ba4987b

###
POST {{api7}}
Content-Type: application/json

{
"codigo": "L-1",
"nombre": "Ron",
"marca": "Zacapa",
"precioBotella": 40000,
"precioUnitario": 4000,
"nacionalidad": "Guatemala",
"restaurante": "Piccola Stella"
}

###
DELETE {{api7}}/660c86ce12f2dc536ba4987d

###
GET {{api8}}

###
GET {{api8}}/660c89cc3f105f392889ee58

###
POST {{api8}}
Content-Type: application/json

{
"codigo": "V-1",
"nombre": "Porto",
"marca": "Ferreira",
"precioBotella": 25000,
"precioUnitario": 2500,
"nacionalidad": "Portugal",
"anio":2023,
"restaurante": "Piccola Stella"
}

###
DELETE {{api8}}/660c89cc3f105f392889ee58

###
PATCH {{api8}}/660f82cce3164e383e98ddeb
Content-Type: application/json

{
"codigo": "V-1",
"nombre": "Porto",
"marca": "asfsadf",
"precioBotella": 25000,
"precioUnitario": 2500,
"nacionalidad": "asdfasdf",
"anio":2023,
"restaurante": "Piccola Stella"
}

###
GET {{api9}}

###
GET {{api9}}/660cd25de4788ba69b3a2b6a

###
POST {{api9}}
Content-Type: application/json

{
"codigo": "M-1",
"nombre": "Ferreira",
"descripcion": "Marca de vinos tipo Oporto de Portugal",
"nacionalidad": "Portugal",
"empresa":"Vinos y mas",
"telefono": 88752376
}

###
DELETE {{api9}}/660f6d894954d5ae613424f7

###
PATCH {{api9}}/660f7aa22d3da6d69e2460d2
Content-Type: application/json

{
"codigo": "M-1",
"nombre": "asdfasdfa",
"descripcion": "Marasdfasdfasdf",
"nacionalidad": "Portugal",
"empresa":"Vinos y mas",
"telefono": 88752376
}

###
GET {{api10}}

###
GET {{api10}}/660e152fd89b57fd05dddf6a

###
POST {{api10}}
Content-Type: application/json

{
"codigo": "COM-1",
"nombre": "Linguini",
"cantidad": 50,
"tipo": "Cereales",
"restaurante":"Piccola Stella",
"marca": "Firenze"
}

###
DELETE {{api10}}/660e152fd89b57fd05dddf6a

###
PATCH {{api10}}/660f75d09c86a56f4d7a4130
Content-Type: application/json

{
"codigo": "COM-1",
"nombre": "Prueba actualiza",
"cantidad": 50,
"tipo": "Cereales",
"restaurante":"Picfgddsgfhdfg",
"marca": "Firenze"
}

###
GET {{api11}}

###
GET {{api11}}/660e1823949b836f0fddeb22

###
POST {{api11}}
Content-Type: application/json

{
"codigo": "TEC-1",
"nombre": "Computadora",
"marca": "Dell",
"restaurante":"Piccola Stella",
"cantidad": 3,
"descripcion": "Equipo de recepcion, cajas, administracion y cocina"
}

###
DELETE {{api11}}/660f70a9a05397ea25618ff4

###
PATCH {{api11}}/660f811d92d572dc120f9eb2
Content-Type: application/json

{
"codigo": "TEC-1",
"nombre": "asdfasdf",
"marca": "Dell",
"restaurante":"Piccola Stella",
"cantidad": 3,
"descripcion": "Equipo de recepcion, cajas, administracion y cocina"
}

###
GET {{api12}}

###
GET {{api12}}/660e1a34a6971bd37a6a403c

###
POST {{api12}}
Content-Type: application/json

{
"codigo": "ADM-1",
"nombre": "Administrador de Sistema"
}

###
DELETE {{api12}}/660f6e8649fd0170f8398274

###
PATCH {{api12}}/660e1a34a6971bd37a6a403c
Content-Type: application/json

{
"codigo": "ADM-1",
"nombre": "aSDasdAS de Sistema"
}


###
GET {{api13}}

###
GET {{api13}}/660f6a78e6d1a22070cbe413

###
POST {{api13}}
Content-Type: application/json

{
"codigo": "PAS-1",
"nombre": "Pasta",
"ingredientes": "Pasta, carne molida, salsa de tomate, queso ricotta, mozzarella",
"precio": 7500,
"descripcion": "Deliciosa lasagna con capas de pasta, carne y queso"
}

###
DELETE {{api13}}/660f6a78e6d1a22070cbe413

###
PATCH {{api13}}/660f6a78e6d1a22070cbe413
Content-Type: application/json

{
"codigo": "PAS-1",
"nombre": "Huevo",
"ingredientes": "asdfasdfasdf",
"precio": 7500,
"descripcion": "Deliciosa lasagna con capas de pasta, carne y queso"
}

###
GET {{api14}}

###
GET {{api14}}/660e20bb3057ebf063ea3835

###
POST {{api14}}
Content-Type: application/json

{
"codigo": "BG-1",
"nombre": "San Pellegrino Limon",
"precio": 2200,
"restaurante": "Piccola Stella"
}

###
DELETE {{api14}}/660f6b3e6685a2702e61a976

###
PATCH {{api14}}/660f78856470dac238a3b286
Content-Type: application/json

{
"codigo": "BG-1",
"nombre": "San asdfasdfasdf Limon",
"precio": 2200,
"restaurante": "Piccola Stella"
}

###
GET {{api15}}/660f6b3e6685a2702e61a976

###
GET {{api15}}

###
GET {{api15}}/660f65b37df9e6d1e523980d

###
POST {{api15}}
Content-Type: application/json

{
"codigo": "BC-1",
"nombre": "Espresso",
"precio": 1500,
"restaurante": "Piccola Stella"
}

###
DELETE {{api15}}/660f65b37df9e6d1e523980d

###
PATCH {{api15}}/660f73fbde26fe74ec609ad1
Content-Type: application/json

{
"codigo": "SDFGSDFG-1",
"nombre": "dIEGO",
"precio": 32333,
"restaurante": "ASDFWEEDSSAD SDFGSDFGS"
}

###
GET {{api16}}

###
GET {{api16}}/660f66786a0a3f0ae05892fd

###
POST {{api16}}
Content-Type: application/json

{
"codigo": "BH-1",
"nombre": "Frozen Capuccino",
"precio": 2000,
"restaurante": "Piccola Stella"
}

###
DELETE {{api16}}/660e24b8440981c1b9f7fb69

###
PATCH {{api16}}/660f67d5a5ebd8af0edc2432
Content-Type: application/json

{
"codigo": "SDFGSDFG-1",
"nombre": "dIEGO",
"precio": 32333,
"restaurante": "ASDFWEEDSSAD SDFGSDFGS"
}